raiden-network/raiden-libs

raiden_libs/blockchain.py
raiden_libs/contracts.py

The BlockchainListener now monitors all events with a given ABI.

Listen to all events with a given ABI, not just a given contract

---

raiden_libs/exceptions.py
raiden_libs/messages/__init__.py
raiden_libs/messages/balance_proof.py
raiden_libs/messages/deserializer.py
raiden_libs/messages/json_schema.py
raiden_libs/messages/message.py
raiden_libs/properties/__init__.py
raiden_libs/properties/address.py
raiden_libs/test/conftest.py
raiden_libs/test/fixtures/address.py
raiden_libs/test/mocks/client.py
raiden_libs/test/test_messages.py
requirements.txt
setup.py

- move simple mocked client to raiden-libs repo
- balance proof message type is also included

Move mock client from MS to raiden-libs

---

raiden_libs/test/fixtures/client.py
raiden_libs/test/fixtures/web3.py
requirements.txt

- replaced contract constructor and method call
- also bumps required web3 version to b13

Remove deprecated web3 calls

---

raiden_libs/blockchain.py

splits `_update` method into several easily manageable parts

improve readability of blockchain's _update method

---

raiden_libs/test/mocks/dummy_transport.py

Adds a `DummyTransport` mock for use in tests.

Add transport mock

---

raiden_libs/exceptions.py
raiden_libs/messages/deserializer.py
raiden_libs/messages/fee_info.py
raiden_libs/messages/message.py
raiden_libs/test/mocks/client.py
tests/test_client_mock.py
tests/test_messages.py

This are some changes required for the PFS:
- Add an optional type variable for message deserialisation
- Add binary serialisation to FeeInfo
- Add `fee_info` function to the mock raiden client

Typed deserialisation

---

raiden_libs/test/mocks/client.py
tests/test_client_mock.py

- updates updateTransfer method used by the mocked client
- adds some tests to verify channel life cycle

UpdateTransfer for mocked client

---

raiden_libs/messages/fee_info.py
raiden_libs/messages/json_schema.py
raiden_libs/utils/signing.py
tests/test_client_mock.py
tests/test_messages.py

Definition as here: raiden-network/raiden-pathfinding-service#55

Define fee format

---

raiden_libs/network/matrix/__init__.py
raiden_libs/network/matrix/client.py
raiden_libs/network/matrix/room.py
raiden_libs/network/matrix/utils.py
requirements.txt

This is ported from the current WIP Raiden matrix implementation.
**IMPORTANT:** The second commit in this PR needs to be deleted before merging. It's only here to make the package installable until ethereum/eth-tester#81 is fixed

Add gevent compatible matrix client

---

raiden_libs/messages/json_schema.py
raiden_libs/messages/paths_reply.py
raiden_libs/messages/paths_request.py
raiden_libs/test/mocks/client.py
tests/test_messages.py

Adding a source address to request_paths, as it currently cannot be determined over matrix.

adding source address to request_paths

---

raiden_libs/test/mocks/client.py

Fixing missing source address in request_paths method.

Updating mock_client_transport to work with None default.

---

.travis.yml
raiden_libs/contract.py
raiden_libs/private_contract.py
raiden_libs/test/fixtures/web3.py
raiden_libs/utils/contracts.py
raiden_libs/utils/private_key.py
raiden_libs/utils/signing.py
requirements.txt
requirements_dev.txt

Trying to cleanup my mess.
https://github.com/ulope/raiden-libs/commit/63c8162e0435ff7fec91ecf07098bbb65ca4ded2

remove pinning of eth-tester now that dependency cycle has been fixed

---

raiden_libs/messages/balance_proof.py
raiden_libs/messages/fee_info.py
raiden_libs/messages/monitor_request.py
raiden_libs/messages/paths_reply.py
raiden_libs/messages/paths_request.py
raiden_libs/utils/contracts.py

- also adds a method to recover signers of the signed data

Update MonitorRequest to use new MSC data

---

raiden_libs/messages/json_schema.py
raiden_libs/messages/monitor_request.py
raiden_libs/test/mocks/client.py
tests/test_messages.py

- sender can be recovered using the signature

Remove reward proof sender field

---

raiden_libs/network/matrix/room.py

This have slipped in, fix it for raiden-network/raiden#1427

Remove ethereum logging

---

.travis.yml

just runs the setup.py to make sure things are running smoothly

run setup.py to tests requirements

---

raiden_libs/private_contract.py

required for the deployment script

PrivateContract: enable constructor call

---

raiden_libs/private_contract.py
setup.cfg

- plus isort config in setup.cfg

Fix use of gas price in the PrivateContract

---

raiden_libs/transport/matrix.py

Use limit argument in get_room_events

---

raiden_libs/network/matrix/client.py

This function introduces a post-sync hook (Callable) to be provided by users of the MatrixClient so that the hook gets called after every sync. This is added to be able to store "syncToken" as the transport's last updated timestamp to be used later on to define where the sync should start.
This is part of an overall fix in the following PR: https://github.com/raiden-network/raiden/pull/3090

Post sync hook
